kernel: use %zd instead of %ld
make compiler shut up in old device (armv7l)
../drivers/kernelsu/ksud.c: In function 'read_proxy':
../drivers/kernelsu/ksud.c:383:9: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'ssize_t' [-Werror=format=]
         pr_info("read_proxy: append error, totally appended %ld\n", ksu_rc_pos);
         ^
../drivers/kernelsu/ksud.c:385:9: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'size_t' [-Werror=format=]
         pr_info("read_proxy: append %ld\n", append_count);
         ^
../drivers/kernelsu/ksud.c: In function 'read_iter_proxy':
../drivers/kernelsu/ksud.c:415:9: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'ssize_t' [-Werror=format=]
         pr_info("read_iter_proxy: append error, totally appended %ld\n",
         ^
../drivers/kernelsu/ksud.c:418:9: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'size_t' [-Werror=format=]
         pr_info("read_iter_proxy: append %ld\n", append_count);
         ^
cc1: all warnings being treated as errors
make[3]: *** [../scripts/Makefile.build:334: drivers/kernelsu/ksud.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [../scripts/Makefile.build:648: drivers/kernelsu] Error 2
make[2]: *** Waiting for unfinished jobs....